name: okteto-stack
services:
  postgres:
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=demo
    image: postgres:14
    ports:
      - 5432
    volumes:
      - /var/lib/postgresql/data/